### ISSUE TITLE
Cópia de conteúdo da Live de Python

### ISSUE THREAD

**Issue by filipecifali** [CarlosHenrique13/Desenvolvendo-Ti#1]
Porque você está copiando o conteúdo da Live de Python descaradamente e pedindo dinheiro como se você estivesse fazendo algum trabalho envolvendo isso?

Dá pra ver claramente o path de caminho do Eduardo o verdadeiro criador do conteúdo.

![image_2022-05-10_16-48-50](https://user-images.githubusercontent.com/975041/167711994-cd7bb65c-43a1-44f8-bfa2-ff4b2a4bdc60.png)

**Comment by CarlosHenrique13** [comment]
O conteúdo e permitido a reutilização eu edito recrio o slide e separa em
vídeos menores  vídeos de acordo o YouTube eu estou seguindo as normas


Em ter, 10 de mai de 2022 17:00, Filipe Cifali Stangler <
***@***.***> escreveu:

**Comment by CarlosHenrique13** [comment]
Caso ele queira que eu remova o conteúdo peça para ele me enviar um e-mail
que eu apago

Em ter, 10 de mai de 2022 17:00, Filipe Cifali Stangler <
***@***.***> escreveu:

**Comment by filipecifali** [comment]
Não isso não é permitido, o que você faz não passa de plágio nesse caso. Você não está transformando o conteúdo em algo novo, está apenas cortando e repostando o mesmo.

**Comment by CarlosHenrique13** [comment]
Está bem remover eu o conteúdo daqui algumas horas está fora do ar

Peço desculpas

Em ter, 10 de mai de 2022 17:08, Filipe Cifali Stangler <
***@***.***> escreveu:

**Comment by dunossauro** [comment]
```
O conteúdo e permitido a reutilização eu edito recrio o slide e separa em
vídeos menores  vídeos de acordo o YouTube eu estou seguindo as normas
```

@CarlosHenrique13, não é assim que o creative commons funciona.

Você pode usar o conteúdo produzido por mim, mas não pode omitir a fonte original. Você **deve** deixar explícito que esse conteúdo é criado ou baseado no conteúdo de outra pessoa.

**Comment by CarlosHenrique13** [comment]
Se eu editar o vídeo e colocar uma dedicatória e informa a fonte do
conteúdo que o seu canal no final do vídeo ou no início eu posso utilizar?


Em ter, 10 de mai de 2022 17:17, Eduardo Mendes ***@***.***>
escreveu:

**Comment by infoslack** [comment]
Olha, melhor não fazer mais isso.
Pega mal e você pode se complicar.

**Comment by leoramos086** [comment]
Fez a mesma coisa com o de Java copiando... ai o cara não falou nada... ele queria fazer denovo...
https://www.youtube.com/channel/UC9xBCxrM6qLuJYJX18LGRBw

Para né... lógico que é errado mano!

**Comment by CarlosHenrique13** [comment]
Ok desculpa

Em ter, 10 de mai de 2022 17:41, Leandro Ramos de Oliveira <
***@***.***> escreveu:

**Comment by luzfcb** [comment]
Pegar mal é pouco, você removeu qualquer menção ao @dunossauro, removeu o rosto dele dos videos. Você ainda teve a coragem de incluir código QR de PIX pedindo dinheiro. Ao meu ver, se enquadra nos artigos 171 e 184 do código penal, tendo como pena de 1 a 5 anos de prisão, basta o @dunossauro te acionar na justiça. O teu nome completo e 6 digitos do CPF ele consegue facilmente via o código QR do teu PIX do Banco Inter que você deixou nos videos...

**Comment by CarlosHenrique13** [comment]
Peço muitas desculpas eu só gosto do conteúdo ele e pensei que não tava
fazendo mal estou muito arrependido estou privando todos os vídeo por favor
só menor de idade não tinha ideia direito do que estava fazendo

Em ter, 10 de mai de 2022 17:58, Fábio C. Barrionuevo da Luz <
***@***.***> escreveu:

**Comment by leoramos086** [comment]
Gostou tanto que queria ganhar uma grana com ele e não deu credito nenhum para quem fez. Stunks!!

**Comment by CarlosHenrique13** [comment]
Eu errei me desculpe o único dinheiro que eu recebi foi 18 reais vcs querem
que eu transfiro para o Eduardo Mendes eu transfiro não tem problema em
tranferir o que eu ganhei pessoa perdão

Em ter, 10 de mai de 2022 18:10, Leandro Ramos de Oliveira <
***@***.***> escreveu:

**Comment by leoramos086** [comment]
Brother... sua edição é muito legal... vc sabe fazer a parada.... Estuda, pega as ideias de vídeos ... mas você não precisa disso. Posta sobre sua evolução de aprendizado. Seu próprio conteúdo, você é capaz!! 

![Captura de tela 2022-05-10 181628](https://user-images.githubusercontent.com/11160931/167723349-fe7b080d-6835-4e09-b79b-dc2b1675ebaa.jpg)

**Comment by CarlosHenrique13** [comment]
Ta bom, aprendi com meu erro pessoa muitas desculpas.

Em ter, 10 de mai de 2022 18:18, Leandro Ramos de Oliveira <
***@***.***> escreveu:

**Comment by filipecifali** [comment]
Estou fechando a issue como já foi dada a atenção devida ao assunto. Sucesso e espero ver **seu** conteúdo em futuros eventos para ajudar a comunidade de volta.

**Comment by CarlosHenrique13** [comment]
Obrigado.

Em qua, 11 de mai de 2022 13:15, Filipe Cifali Stangler <
***@***.***> escreveu:
